package com.example.myzulipapp.ui.theme

import androidx.compose.ui.graphics.Color

val theme_light_blue_yonder = Color(0xFF517DA2)
val theme_light_azureish_white = Color(0xFFD5E7F7)
val theme_light_blue_steel = Color(0xFF66A9E0)
val theme_light_silver_lake_blue = Color(0xFF5A8FBB)
val theme_light_white = Color(0xFFFFFFFF)
val theme_light_blue_jeans = Color(0xFF50A7EA)
val theme_light_primary_text_color = Color(0xFF000000)
val theme_light_secondary_text_color = Color(0xFF8B8C8E)
val theme_light_roman_silver = Color(0xFF889197)
val theme_light_hint_color = Color(0xFFA8A8A8)
val theme_light_nyanza = Color(0xFFEFFEDD)
val theme_light_background = Color(0xFFFFFFFF)
val theme_light_chat_background = Color(0xFF91BB8D)
val theme_light_own_reaction_background = Color(0xFF72B5E9)
val theme_light_user_reaction_background = Color(0xFFDCF7CE)
val theme_light_logo_progress_bar = Color(0xFF444444)
val theme_light_shimmer = Color(0xFFFFFFFF)
val theme_light_user_name = Color(0xFF8E96E7)
val theme_light_own_message_time = Color(0xFF76AC63)
val theme_light_user_message_time = Color(0xFFA1AAB3)
val theme_light_error = Color(0xFFBA1A1A)

val theme_dark_gunmetal = Color(0xFF252D3A)
val theme_dark_cool_grey = Color(0xFF8B97A3)
val theme_dark_french_sky_blue = Color(0xFF65ADFF)
val theme_dark_carolina_blue = Color(0xFF5EA3DE)
val theme_dark_gunmetal_midnight = Color(0xFF233040)
val theme_dark_dark_gunmetal = Color(0xFF1C242F)
val theme_dark_blue_jeans = Color(0xFF50A7EA)
val theme_dark_primary_text_color = Color(0xFFFFFFFF)
val theme_dark_secondary_text_color = Color(0xFF7C8A98)
val theme_dark_roman_silver = Color(0xFF889197)
val theme_dark_hint_color = Color(0xFF7C8A98)
val theme_dark_royal_purple = Color(0xFF8247BB)
val theme_dark_white = Color(0xFFFFFFFF)
val theme_dark_background = Color(0xFF1D2733)
val theme_dark_chat_background = Color(0xFF141C29)
val theme_dark_own_reaction_background = Color(0xFF72B5E9)
val theme_dark_user_reaction_background = Color(0xFF8E60CD)
val theme_dark_logo_progress_bar = Color(0xFF444444)
val theme_dark_shimmer = Color(0xFF000000)
val theme_dark_user_name = Color(0xFF8E96E7)
val theme_dark_own_message_time = Color(0xFFFFFFFF)
val theme_dark_user_message_time = Color(0xFF728290)
val theme_dark_error = Color(0xFFFFB4AB)
